/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OdontoSysPantalla;

import OdontoSysModelo.Datos;
import OdontoSysUtil.NewHibernateUtil;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.Iterator;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author user
 */
public class DatosEmpresa extends javax.swing.JFrame {

    /**
     * Variables
     */
    
    Datos dat = null;
    
    /**
     *
     */
    public DatosEmpresa() {
        initComponents();
        
        limpiar();
        dat = new Datos();
        dat = obtenerDatos();
        setear();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmp = new javax.swing.JTextField();
        jTextFieldProp = new javax.swing.JTextField();
        jTextFieldAct = new javax.swing.JTextField();
        jTextFieldRUC = new javax.swing.JTextField();
        jTextFieldDir = new javax.swing.JTextField();
        jTextFieldCiu = new javax.swing.JTextField();
        jTextFieldTel = new javax.swing.JTextField();
        jButtonMod = new javax.swing.JButton();
        jButtonGua = new javax.swing.JButton();
        jButtonCanc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Datos de la Empresa");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del propietario");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("RUC");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Dirección de la casa matriz");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Actividad económica de la empresa");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Teléfono");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Ciudad - País");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Nombre de la Empresa");

        jTextFieldEmp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jTextFieldProp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jTextFieldAct.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jTextFieldRUC.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jTextFieldDir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jTextFieldCiu.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jTextFieldTel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jButtonMod.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/modificar.png"))); // NOI18N
        jButtonMod.setText("Modificar");
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jButtonGua.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonGua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/guardar.png"))); // NOI18N
        jButtonGua.setText("Guardar");
        jButtonGua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuaActionPerformed(evt);
            }
        });

        jButtonCanc.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonCanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/eliminar.png"))); // NOI18N
        jButtonCanc.setText("Cancelar");
        jButtonCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldProp, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jButtonMod))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAct, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldDir, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCiu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButtonGua)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonCanc)))))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(134, 134, 134))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMod)
                    .addComponent(jButtonGua)
                    .addComponent(jButtonCanc))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuaActionPerformed
        // Esta información se sobreescribe sobre el id 1 de la tabla datos
        dat.setNombreEmpresa(jTextFieldEmp.getText());
        dat.setNombrePropietario(jTextFieldProp.getText());
        dat.setRuc(jTextFieldRUC.getText());
        dat.setActividad(jTextFieldAct.getText());
        dat.setDireccion(jTextFieldDir.getText());
        dat.setCiudad(jTextFieldCiu.getText());
        dat.setTelefono(jTextFieldTel.getText());
        
        validar();
        
        setear();
        
    }//GEN-LAST:event_jButtonGuaActionPerformed

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        
        jButtonGua.setVisible(true);
        
        jTextFieldEmp.setEditable(true);
        jTextFieldProp.setEditable(true);
        jTextFieldRUC.setEditable(true);
        jTextFieldAct.setEditable(true);
        jTextFieldDir.setEditable(true);
        jTextFieldCiu.setEditable(true);
        jTextFieldTel.setEditable(true);
        
        jButtonMod.setVisible(false);
    }//GEN-LAST:event_jButtonModActionPerformed

    private void jButtonCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancActionPerformed
        limpiar();
        dispose();
    }//GEN-LAST:event_jButtonCancActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCanc;
    private javax.swing.JButton jButtonGua;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldAct;
    private javax.swing.JTextField jTextFieldCiu;
    private javax.swing.JTextField jTextFieldDir;
    private javax.swing.JTextField jTextFieldEmp;
    private javax.swing.JTextField jTextFieldProp;
    private javax.swing.JTextField jTextFieldRUC;
    private javax.swing.JTextField jTextFieldTel;
    // End of variables declaration//GEN-END:variables

    private void validar() {
        
        if(dat.getNombreEmpresa() == null && dat.getNombreEmpresa().length() > 100){
            JOptionPane.showMessageDialog(null, "Favor complete el nombre de la Empresa", "Datos de la Empresa", JOptionPane.INFORMATION_MESSAGE);   
        }else if(dat.getNombrePropietario() == null && dat.getNombrePropietario().length() > 100){
            JOptionPane.showMessageDialog(null, "Favor complete el nombre del Propietario", "Datos de la Empresa", JOptionPane.INFORMATION_MESSAGE);
        }else if(dat.getRuc() == null && dat.getRuc().length() > 11){
            JOptionPane.showMessageDialog(null, "Favor complete el RUC de la Empresa, hasta 10 caracteres", "Datos de la Empresa", JOptionPane.INFORMATION_MESSAGE);
        }else if(dat.getActividad() == null && dat.getActividad().length() > 200){
            JOptionPane.showMessageDialog(null, "Favor complete la actividad de la Empresa, hasta 200 caracteres", "Datos de la Empresa", JOptionPane.INFORMATION_MESSAGE);
        }else if(dat.getDireccion() == null && dat.getDireccion().length() > 100){
            JOptionPane.showMessageDialog(null, "Favor complete la dirección de la Empresa, hasta 100 caracteres", "Datos de la Empresa", JOptionPane.INFORMATION_MESSAGE);
        }else if(dat.getCiudad() == null && dat.getCiudad().length() > 50){
            JOptionPane.showMessageDialog(null, "Favor complete la ciudad - pais de la Empresa, hasta 50 caracteres", "Datos de la Empresa", JOptionPane.INFORMATION_MESSAGE);
        }else if(dat.getTelefono() == null && dat.getTelefono().length() > 10){
            JOptionPane.showMessageDialog(null, "Favor complete el teléfono de la Empresa, hasta 10 caracteres", "Datos de la Empresa", JOptionPane.INFORMATION_MESSAGE);
        }else{
            guardar();
        }
    }

    private void guardar() {
        
        Session sesion;
        try{
            sesion = NewHibernateUtil.getSessionFactory().openSession();
            Transaction tr = sesion.beginTransaction();            
            sesion.merge(dat);
            tr.commit();
            sesion.close();
        }catch(HibernateException ex){
            System.out.println(ex.getMessage());
           JOptionPane.showMessageDialog(null,ex.getMessage(), "Insertar Datos de Empresa", WIDTH );
        }  
        
    }

    private Datos obtenerDatos() {
        Session sesion = null;
        Datos d = null;
        try{
            sesion = NewHibernateUtil.getSessionFactory().openSession();
            sesion.beginTransaction();
            
            String cons = "FROM Datos WHERE iddatos = 1";
            d = new Datos();
            d = (Datos) sesion.createQuery(cons).uniqueResult();
            
            sesion.close();
            
        }catch(HibernateException ex){
            System.out.println(ex.getMessage());
           JOptionPane.showMessageDialog(null,ex.getMessage(), "Recuperar Datos de Empresa", WIDTH );
        }
        
        return d;
    }

    private void setear() {
        
        jButtonGua.setVisible(false);
        jButtonMod.setVisible(true);
        
        jTextFieldEmp.setEditable(false);
        jTextFieldProp.setEditable(false);
        jTextFieldRUC.setEditable(false);
        jTextFieldAct.setEditable(false);
        jTextFieldDir.setEditable(false);
        jTextFieldCiu.setEditable(false);
        jTextFieldTel.setEditable(false);
        
        if(dat != null){
            jTextFieldEmp.setText(dat.getNombreEmpresa());
            jTextFieldProp.setText(dat.getNombrePropietario());
            jTextFieldRUC.setText(dat.getRuc());
            jTextFieldAct.setText(dat.getActividad());
            jTextFieldDir.setText(dat.getDireccion());
            jTextFieldCiu.setText(dat.getCiudad());
            jTextFieldTel.setText(dat.getTelefono());
        }
    
    }

    private void limpiar() {
        
        dat = null;
        jTextFieldEmp.setText("");
        jTextFieldProp.setText("");
        jTextFieldRUC.setText("");
        jTextFieldAct.setText("");
        jTextFieldDir.setText("");
        jTextFieldCiu.setText("");
        jTextFieldTel.setText("");
    
    }
}
