/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OdontoSysPantalla;

import OdontoSysControlador.CiudadControlador;
import OdontoSysControlador.ConvenioControlador;
import OdontoSysControlador.EmpresaControlador;
import OdontoSysModelo.Ciudad;
import OdontoSysModelo.Convenio;
import OdontoSysModelo.Empresa;
import OdontoSysModelo.FacturaEmpresa;
import OdontoSysModelo.OrdenEmpresa;
import OdontoSysModelo.Paciente;
import OdontoSysModelo.ReciboEmpresa;
import OdontoSysModelo.Usuario;
import OdontoSysPantallaAuxiliares.ObtenerEmpresa;
import OdontoSysUtil.Configuraciones;
import OdontoSysUtil.NewHibernateUtil;
import OdontoSysVista.EmpresaVista;
import static java.awt.image.ImageObserver.WIDTH;
import static java.lang.Integer.parseInt;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author user
 */
public class Empresas extends javax.swing.JFrame {

    //Variables Globales
    Empresa empresaActual = null;
    public static Usuario user = null;
        
    Session sesion = null;
    Transaction tr = null;
    
    DefaultTableModel tablaConvenios = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    DefaultTableModel tablaEstado = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    DefaultTableModel tablaPendientes = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    ArrayList<Paciente> listaPac = null;
    ArrayList<FacturaEmpresa> listaEst = null;
    ArrayList<ReciboEmpresa> listaRec = null;
    ArrayList<OrdenEmpresa> listaOrd = null;
    ArrayList<Convenio> listaconvenios = null;
    ArrayList<Ciudad> ciudades = null;
    
    DecimalFormat formateador = new DecimalFormat("###,###");
    SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
    
    
    
    public Empresas() {
        initComponents();
        BotonInvisibles();
        recuperarCiudades();
        inicializarTablas();
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDatos = new javax.swing.JPanel();
        jLabelDNombres = new javax.swing.JLabel();
        jLabelDCI = new javax.swing.JLabel();
        jLabelDTel = new javax.swing.JLabel();
        jLabelDDireccion = new javax.swing.JLabel();
        jLabelDEmail = new javax.swing.JLabel();
        jLabelDEmail2 = new javax.swing.JLabel();
        jLabelDEmail3 = new javax.swing.JLabel();
        jLabelNombContacto = new javax.swing.JLabel();
        jTextFieldDNombres = new javax.swing.JTextField();
        jTextFieldRUC = new javax.swing.JTextField();
        jTextFieldDTel = new javax.swing.JTextField();
        jTextFieldDDireccion = new javax.swing.JTextField();
        jTextFieldDEmail = new javax.swing.JTextField();
        jTextFieldNombreContacto = new javax.swing.JTextField();
        jTextFieldTeléfonoContacto = new javax.swing.JTextField();
        jTextFieldObservaciones = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonGuardarModificacion = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelnomb = new javax.swing.JLabel();
        jLabelruc = new javax.swing.JLabel();
        jLabeltel = new javax.swing.JLabel();
        jLabeldir = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        jLabelncon = new javax.swing.JLabel();
        jLabeltcon = new javax.swing.JLabel();
        jLabelobs = new javax.swing.JLabel();
        jLabelCiudad = new javax.swing.JLabel();
        jCBciudad = new javax.swing.JComboBox();
        jPanelConvenios = new javax.swing.JPanel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jButtonInsertarConvenio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConvenios = new javax.swing.JTable();
        jPanelPendientes = new javax.swing.JPanel();
        jLabelTitulo3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePendientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPendiente = new javax.swing.JTextField();
        jButtonFacturar = new javax.swing.JButton();
        jPanelEstadoCuenta = new javax.swing.JPanel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEstadoCuenta = new javax.swing.JTable();
        jButtonRealizarPago = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSaldo = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelDNombres.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDNombres.setText("Nombres");

        jLabelDCI.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDCI.setText("RUC");

        jLabelDTel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDTel.setText("Teléfono");

        jLabelDDireccion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDDireccion.setText("Direccion");

        jLabelDEmail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDEmail.setText("Email");

        jLabelDEmail2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDEmail2.setText("Teléfono Contacto");

        jLabelDEmail3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDEmail3.setText("Observaciones");

        jLabelNombContacto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelNombContacto.setText("Nombre Contacto");

        jTextFieldDNombres.setEditable(false);
        jTextFieldDNombres.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldDNombres.setToolTipText("");
        jTextFieldDNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNombresActionPerformed(evt);
            }
        });
        jTextFieldDNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDNombresFocusLost(evt);
            }
        });
        jTextFieldDNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PacienteKeyReleased(evt);
            }
        });

        jTextFieldRUC.setEditable(false);
        jTextFieldRUC.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldRUC.setToolTipText("");
        jTextFieldRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRUCActionPerformed(evt);
            }
        });
        jTextFieldRUC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRUCFocusLost(evt);
            }
        });
        jTextFieldRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PacienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soloNumerosKeyTyped(evt);
            }
        });

        jTextFieldDTel.setEditable(false);
        jTextFieldDTel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldDTel.setToolTipText("");
        jTextFieldDTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDTelActionPerformed(evt);
            }
        });
        jTextFieldDTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDTelFocusLost(evt);
            }
        });
        jTextFieldDTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PacienteKeyReleased(evt);
            }
        });

        jTextFieldDDireccion.setEditable(false);
        jTextFieldDDireccion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldDDireccion.setToolTipText("");
        jTextFieldDDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDDireccionActionPerformed(evt);
            }
        });
        jTextFieldDDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDDireccionFocusLost(evt);
            }
        });
        jTextFieldDDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PacienteKeyReleased(evt);
            }
        });

        jTextFieldDEmail.setEditable(false);
        jTextFieldDEmail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldDEmail.setToolTipText("");
        jTextFieldDEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDEmailActionPerformed(evt);
            }
        });
        jTextFieldDEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDEmailFocusLost(evt);
            }
        });
        jTextFieldDEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PacienteKeyReleased(evt);
            }
        });

        jTextFieldNombreContacto.setEditable(false);
        jTextFieldNombreContacto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldNombreContacto.setToolTipText("");
        jTextFieldNombreContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreContactoActionPerformed(evt);
            }
        });
        jTextFieldNombreContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreContactoFocusLost(evt);
            }
        });
        jTextFieldNombreContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreContactoPacienteKeyReleased(evt);
            }
        });

        jTextFieldTeléfonoContacto.setEditable(false);
        jTextFieldTeléfonoContacto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldTeléfonoContacto.setToolTipText("");
        jTextFieldTeléfonoContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTeléfonoContactoActionPerformed(evt);
            }
        });
        jTextFieldTeléfonoContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTeléfonoContactoFocusLost(evt);
            }
        });
        jTextFieldTeléfonoContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTeléfonoContactoPacienteKeyReleased(evt);
            }
        });

        jTextFieldObservaciones.setEditable(false);
        jTextFieldObservaciones.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldObservaciones.setToolTipText("");
        jTextFieldObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldObservacionesActionPerformed(evt);
            }
        });
        jTextFieldObservaciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldObservacionesFocusLost(evt);
            }
        });
        jTextFieldObservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldObservacionesPacienteKeyReleased(evt);
            }
        });

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/guardar.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setActionCommand("");
        jButtonGuardar.setAutoscrolls(true);
        jButtonGuardar.setMaximumSize(new java.awt.Dimension(130, 30));
        jButtonGuardar.setMinimumSize(new java.awt.Dimension(130, 30));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonGuardarModificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/ingresar.png"))); // NOI18N
        jButtonGuardarModificacion.setText("Modificar");
        jButtonGuardarModificacion.setActionCommand("");
        jButtonGuardarModificacion.setAutoscrolls(true);
        jButtonGuardarModificacion.setMaximumSize(new java.awt.Dimension(130, 30));
        jButtonGuardarModificacion.setMinimumSize(new java.awt.Dimension(130, 30));
        jButtonGuardarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarModificacionActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelTitulo.setText("Datos de la Empresa");

        jLabelnomb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelnomb.setForeground(new java.awt.Color(255, 0, 0));
        jLabelnomb.setText("El nombre debe tener entre 3 y 30 caracteres");
        jLabelnomb.setToolTipText("");

        jLabelruc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelruc.setForeground(new java.awt.Color(255, 0, 0));
        jLabelruc.setText("El RUC debe tener entre 6 y 15 caracteres");
        jLabelruc.setToolTipText("");

        jLabeltel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabeltel.setForeground(new java.awt.Color(255, 0, 0));
        jLabeltel.setText("El teléfeno debe tener entre 6 y 20 caracteres");
        jLabeltel.setToolTipText("");

        jLabeldir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabeldir.setForeground(new java.awt.Color(255, 0, 0));
        jLabeldir.setText("La dirección debe tener entre 5 y 50 caracteres");
        jLabeldir.setToolTipText("");

        jLabelemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelemail.setForeground(new java.awt.Color(255, 0, 0));
        jLabelemail.setText("Hasta 30 caracteres permitidos");
        jLabelemail.setToolTipText("");

        jLabelncon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelncon.setForeground(new java.awt.Color(255, 0, 0));
        jLabelncon.setText("Entre 5 y 50 caracteres permitidos");
        jLabelncon.setToolTipText("");

        jLabeltcon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabeltcon.setForeground(new java.awt.Color(255, 0, 0));
        jLabeltcon.setText("Hasta 20 caracteres permitidos");
        jLabeltcon.setToolTipText("");

        jLabelobs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelobs.setForeground(new java.awt.Color(255, 0, 0));
        jLabelobs.setText("Hasta 100 caracteres permitidos");
        jLabelobs.setToolTipText("");

        jLabelCiudad.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelCiudad.setText("Ciudad");

        jCBciudad.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jCBciudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDCI)
                            .addComponent(jLabelDTel)
                            .addComponent(jLabelDNombres)
                            .addComponent(jLabelDDireccion)
                            .addComponent(jLabelDEmail3)
                            .addComponent(jLabelCiudad))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDEmail2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDEmail)
                                .addComponent(jLabelNombContacto)))))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextFieldTeléfonoContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextFieldObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextFieldDNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextFieldRUC, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextFieldDTel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextFieldDDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jCBciudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeltcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelnomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelruc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabeltel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabeldir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelncon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addComponent(jLabelobs, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                                        .addComponent(jButtonGuardarModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)))))))
                .addGap(28, 28, 28))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelnomb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDCI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelruc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDTel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDTel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeldir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelncon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTeléfonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltcon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelobs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonGuardarModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Datos", new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/persona.png")), jPanelDatos); // NOI18N

        jPanelConvenios.setPreferredSize(new java.awt.Dimension(790, 379));

        jLabelTitulo1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelTitulo1.setText("Convenios de la Empresa");

        jButtonInsertarConvenio.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonInsertarConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/agregar.png"))); // NOI18N
        jButtonInsertarConvenio.setText("Insertar Convenio");
        jButtonInsertarConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarConvenioActionPerformed(evt);
            }
        });

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTableConvenios.setModel(tablaConvenios);
        jTableConvenios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConveniosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableConvenios);

        javax.swing.GroupLayout jPanelConveniosLayout = new javax.swing.GroupLayout(jPanelConvenios);
        jPanelConvenios.setLayout(jPanelConveniosLayout);
        jPanelConveniosLayout.setHorizontalGroup(
            jPanelConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConveniosLayout.createSequentialGroup()
                .addGroup(jPanelConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConveniosLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabelTitulo1))
                    .addGroup(jPanelConveniosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonInsertarConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelConveniosLayout.setVerticalGroup(
            jPanelConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConveniosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInsertarConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Convenios", new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/orden.png")), jPanelConvenios); // NOI18N

        jLabelTitulo3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelTitulo3.setText("Pendientes de Facturar");

        jTablePendientes.setModel(tablaPendientes);
        jScrollPane4.setViewportView(jTablePendientes);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Total pendiente");

        jTextFieldPendiente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jButtonFacturar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/dinero.png"))); // NOI18N
        jButtonFacturar.setText("Facturar");
        jButtonFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacturarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPendientesLayout = new javax.swing.GroupLayout(jPanelPendientes);
        jPanelPendientes.setLayout(jPanelPendientesLayout);
        jPanelPendientesLayout.setHorizontalGroup(
            jPanelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPendientesLayout.createSequentialGroup()
                .addGroup(jPanelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPendientesLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabelTitulo3))
                    .addGroup(jPanelPendientesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPendientesLayout.createSequentialGroup()
                                .addComponent(jButtonFacturar)
                                .addGap(378, 378, 378)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelPendientesLayout.setVerticalGroup(
            jPanelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPendientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelTitulo3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPendientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFacturar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pendientes", new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/hoja.png")), jPanelPendientes); // NOI18N

        jLabelTitulo2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelTitulo2.setText("Estado de Cuenta de la Empresa");
        jLabelTitulo2.setToolTipText("");

        jTableEstadoCuenta.setModel(tablaEstado);
        jTableEstadoCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEstadoCuentaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableEstadoCuenta);

        jButtonRealizarPago.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonRealizarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/dinero.png"))); // NOI18N
        jButtonRealizarPago.setText("Realizar un Pago");
        jButtonRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarPagoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Saldo hasta la fecha");

        jTextFieldSaldo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelEstadoCuentaLayout = new javax.swing.GroupLayout(jPanelEstadoCuenta);
        jPanelEstadoCuenta.setLayout(jPanelEstadoCuentaLayout);
        jPanelEstadoCuentaLayout.setHorizontalGroup(
            jPanelEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoCuentaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEstadoCuentaLayout.createSequentialGroup()
                        .addComponent(jButtonRealizarPago)
                        .addGap(359, 359, 359)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEstadoCuentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo2)
                .addGap(221, 221, 221))
        );
        jPanelEstadoCuentaLayout.setVerticalGroup(
            jPanelEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo2)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRealizarPago))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estado de Cuenta", new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/grafico.png")), jPanelEstadoCuenta); // NOI18N

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/buscar.png"))); // NOI18N
        jButtonBuscar.setText("Buscar Empresa");
        jButtonBuscar.setMaximumSize(new java.awt.Dimension(150, 30));
        jButtonBuscar.setMinimumSize(new java.awt.Dimension(150, 30));
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(150, 30));
        jButtonBuscar.setRolloverEnabled(false);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonInsertar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/agregar.png"))); // NOI18N
        jButtonInsertar.setText("Insertar");
        jButtonInsertar.setMaximumSize(new java.awt.Dimension(130, 30));
        jButtonInsertar.setMinimumSize(new java.awt.Dimension(130, 30));
        jButtonInsertar.setRolloverEnabled(false);
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jButtonModificar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/modificar.png"))); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.setMaximumSize(new java.awt.Dimension(130, 30));
        jButtonModificar.setMinimumSize(new java.awt.Dimension(130, 30));
        jButtonModificar.setRolloverEnabled(false);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonEliminar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/borrar.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setMaximumSize(new java.awt.Dimension(130, 30));
        jButtonEliminar.setMinimumSize(new java.awt.Dimension(130, 30));
        jButtonEliminar.setRolloverEnabled(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonMenu.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/accesos.png"))); // NOI18N
        jButtonMenu.setText("Volver al menú principal");
        jButtonMenu.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jButtonMenu.setMaximumSize(new java.awt.Dimension(180, 30));
        jButtonMenu.setMinimumSize(new java.awt.Dimension(180, 30));
        jButtonMenu.setPreferredSize(new java.awt.Dimension(180, 30));
        jButtonMenu.setRolloverEnabled(false);
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/eliminar.png"))); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.setMaximumSize(new java.awt.Dimension(130, 30));
        jButtonAtras.setMinimumSize(new java.awt.Dimension(130, 30));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        botonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/actualizar.png"))); // NOI18N
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        sesion = NewHibernateUtil.getSessionFactory().openSession();
        tr = sesion.beginTransaction();
        
        ObtenerEmpresa.sesion = sesion;
        ObtenerEmpresa jDialog= new ObtenerEmpresa(null, true);
        jDialog.setVisible(true);
        empresaActual= jDialog.getReturnStatus();
        if(empresaActual != null){
            escribirEmpresa(empresaActual);
            habilitarBotones();
            deshabilitarDatos();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo recuperar la empresa" , "Obtener Empresa" , JOptionPane.QUESTION_MESSAGE );
        } 
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    
    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        habilitarDatos();
        jButtonGuardarModificacion.setVisible(true);
        jButtonAtras.setVisible(true);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        // TODO add your handling code here:
        habilitarDatos();
        jTextFieldDNombres.requestFocus(rootPaneCheckingEnabled);
        jButtonInsertar.setVisible(false);
        jButtonGuardar.setVisible(true);
        jButtonAtras.setVisible(true);
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
       int eliminar = JOptionPane.showConfirmDialog( null, "Eliminar empresa "+empresaActual.getNombre()+"con RUC "+empresaActual.getRuc()+"??");
        if(JOptionPane.YES_OPTION == eliminar){
            boolean i = EmpresaControlador.EliminarEmpresa(empresaActual, sesion);
            if(i){
                JOptionPane.showMessageDialog(rootPane, "Se eliminó correctamente", "Eliminar Empresa", WIDTH);
                limpiar();
                BotonInvisibles();
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se pudo eliminar empresa", "Eliminar Empresa", WIDTH);
            }
        }else{
            //cancelado
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        limpiar();
        BotonInvisibles();
        this.setVisible(false);//oculta el jFrame actual
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jTextFieldObservacionesPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldObservacionesPacienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldObservacionesPacienteKeyReleased

    private void jTextFieldObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldObservacionesActionPerformed

    private void jTextFieldTeléfonoContactoPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTeléfonoContactoPacienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTeléfonoContactoPacienteKeyReleased

    private void jTextFieldTeléfonoContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTeléfonoContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTeléfonoContactoActionPerformed

    private void jTextFieldNombreContactoPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreContactoPacienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreContactoPacienteKeyReleased

    private void jTextFieldNombreContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreContactoActionPerformed

    private void jButtonGuardarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarModificacionActionPerformed
        boolean v = validaciones();
        if(v){
            actualizarEmpresa(empresaActual);
            if(empresaActual != null && empresaActual.getIdempresa() > 0){
                v = EmpresaVista.validarEmpresa(empresaActual);
                if(v){
                    v = EmpresaControlador.UpdateEmpresa(empresaActual, sesion);
                    if(v){
                        JOptionPane.showMessageDialog(rootPane, "Se modificó correctamente", "Modificar Empresa", WIDTH);
                        deshabilitarDatos();
                        habilitarBotones();
                        jButtonGuardarModificacion.setVisible(false);
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "No se logró actualizar la empresa", "Modificar Empresa", WIDTH);
                    }
                }
            }   
        }
    }//GEN-LAST:event_jButtonGuardarModificacionActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        limpiar();
        BotonInvisibles();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        boolean v = validaciones();
        if(v){
            insertarEmpresa();
            BotonInvisibles();
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void PacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PacienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_PacienteKeyReleased

    private void jTextFieldDEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDEmailActionPerformed

    private void jTextFieldDDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDDireccionActionPerformed

    private void jTextFieldDTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDTelActionPerformed

    private void soloNumerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soloNumerosKeyTyped
        char c = evt.getKeyChar();
        int i = c;
        if( (c < '0' || c > '9') && (i != 8 && i != 9 && i != 13 && i != 45) ){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Este campo sólo admite numeros", "Validez de Campo", WIDTH);
        }
    }//GEN-LAST:event_soloNumerosKeyTyped

    private void jTextFieldRUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRUCActionPerformed

    private void jTextFieldDNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNombresActionPerformed

    private void jButtonRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarPagoActionPerformed
        RecibosEmpresa.empActual = empresaActual;
        RecibosEmpresa.user = user;
        RecibosEmpresa.main(null);
    }//GEN-LAST:event_jButtonRealizarPagoActionPerformed

    private void jButtonFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacturarActionPerformed
        FacturasEmpresas.empActual = empresaActual;
        FacturasEmpresas.listaOrden = listaOrd;
        FacturasEmpresas.user = user;
        FacturasEmpresas.main(null);
    }//GEN-LAST:event_jButtonFacturarActionPerformed

    private void jTableEstadoCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstadoCuentaMouseClicked
        
    }//GEN-LAST:event_jTableEstadoCuentaMouseClicked

    private void jTableConveniosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConveniosMouseClicked
        int fila = jTableConvenios.getSelectedRow();
        Convenio c = listaconvenios.get(fila);
        Convenios.empresaActual = empresaActual;
        Convenios.conv = c;
        Convenios.sesion = sesion;
        Convenios.user = user;
        Convenios.main(null);
    }//GEN-LAST:event_jTableConveniosMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jTextFieldDNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDNombresFocusLost
        String n = jTextFieldDNombres.getText();
        if(n.length() < 3 || n.length() > 30){
            jLabelnomb.setVisible(true);
        }else{
            jLabelnomb.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldDNombresFocusLost

    private void jTextFieldRUCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRUCFocusLost
        String r = jTextFieldRUC.getText();
        if(r.length() < 6 || r.length() > 15){
            jLabelruc.setVisible(true);
        }else{
            jLabelruc.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldRUCFocusLost

    private void jTextFieldDTelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDTelFocusLost
        String t = jTextFieldDTel.getText();
        if(t.length() < 6 || t.length() > 20){
            jLabeltel.setVisible(true);
        }else{
            jLabeltel.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldDTelFocusLost

    private void jTextFieldDDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDDireccionFocusLost
        String d = jTextFieldDDireccion.getText();
        if(d.length() < 5 || d.length() > 50){
            jLabeldir.setVisible(true);
        }else{
            jLabeldir.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldDDireccionFocusLost

    private void jTextFieldDEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDEmailFocusLost
        String e = jTextFieldDEmail.getText();
        if(e.length() > 30){
            jLabelemail.setVisible(true);
        }else{
            jLabelemail.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldDEmailFocusLost

    private void jTextFieldNombreContactoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreContactoFocusLost
        String n = jTextFieldNombreContacto.getText();
        if(n.length() < 5 || n.length() > 50){
            jLabelncon.setVisible(true);
        }else{
            jLabelncon.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldNombreContactoFocusLost

    private void jTextFieldTeléfonoContactoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTeléfonoContactoFocusLost
        String t = jTextFieldTeléfonoContacto.getText();
        if(t.length() > 20){
            jLabeltcon.setVisible(true);
        }else{
            jLabeltcon.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldTeléfonoContactoFocusLost

    private void jTextFieldObservacionesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldObservacionesFocusLost
        String o = jTextFieldObservaciones.getText();
        if(o.length() > 100){
            jLabelobs.setVisible(true);
        }else{
            jLabelobs.setVisible(false);
        }
    }//GEN-LAST:event_jTextFieldObservacionesFocusLost

    private void jButtonInsertarConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarConvenioActionPerformed
        Convenios.user = user;
        Convenios.empresaActual = empresaActual;
        Convenios jFrame = new Convenios();        //Abre Form Convenios
        jFrame.setVisible(true);
    }//GEN-LAST:event_jButtonInsertarConvenioActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        repaintForm();
    }//GEN-LAST:event_botonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Empresas().setVisible(true);
            }
        });

    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonFacturar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonGuardarModificacion;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonInsertarConvenio;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonRealizarPago;
    private javax.swing.JComboBox jCBciudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelDCI;
    private javax.swing.JLabel jLabelDDireccion;
    private javax.swing.JLabel jLabelDEmail;
    private javax.swing.JLabel jLabelDEmail2;
    private javax.swing.JLabel jLabelDEmail3;
    private javax.swing.JLabel jLabelDNombres;
    private javax.swing.JLabel jLabelDTel;
    private javax.swing.JLabel jLabelNombContacto;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelTitulo3;
    private javax.swing.JLabel jLabeldir;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelncon;
    private javax.swing.JLabel jLabelnomb;
    private javax.swing.JLabel jLabelobs;
    private javax.swing.JLabel jLabelruc;
    private javax.swing.JLabel jLabeltcon;
    private javax.swing.JLabel jLabeltel;
    private javax.swing.JPanel jPanelConvenios;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelEstadoCuenta;
    private javax.swing.JPanel jPanelPendientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableConvenios;
    private javax.swing.JTable jTableEstadoCuenta;
    private javax.swing.JTable jTablePendientes;
    private javax.swing.JTextField jTextFieldDDireccion;
    private javax.swing.JTextField jTextFieldDEmail;
    private javax.swing.JTextField jTextFieldDNombres;
    private javax.swing.JTextField jTextFieldDTel;
    private javax.swing.JTextField jTextFieldNombreContacto;
    private javax.swing.JTextField jTextFieldObservaciones;
    private javax.swing.JTextField jTextFieldPendiente;
    private javax.swing.JTextField jTextFieldRUC;
    private javax.swing.JTextField jTextFieldSaldo;
    private javax.swing.JTextField jTextFieldTeléfonoContacto;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        
        jTextFieldDNombres.setText("");
        jTextFieldRUC.setText("");    
        jTextFieldDDireccion.setText("");
        jTextFieldDEmail.setText("");
        jTextFieldDTel.setText("");
        jTextFieldNombreContacto.setText("");
        jTextFieldObservaciones.setText("");
        jTextFieldTeléfonoContacto.setText("");
        jCBciudad.setSelectedIndex(0);
        jTextFieldPendiente.setText("");
        jTextFieldSaldo.setText("");
        
        empresaActual = null;
        
        Configuraciones.limpiarModelo(tablaConvenios);
        Configuraciones.limpiarModelo(tablaEstado);
        Configuraciones.limpiarModelo(tablaPendientes);
        
        listaPac = null;
        listaEst = null;
        listaconvenios = null;
        listaRec = null;
        listaOrd = null;
        
        if(sesion != null){
            tr.commit();
            sesion.close();
            sesion = null;
            tr = null;
        }
        
    }

    

    private void habilitarDatos() {
        jTextFieldDNombres.setEditable(true);
        jTextFieldRUC.setEditable(true);
        jTextFieldDDireccion.setEditable(true);
        jTextFieldDEmail.setEditable(true);
        jTextFieldDTel.setEditable(true);        
        jTextFieldNombreContacto.setEditable(true);
        jTextFieldObservaciones.setEditable(true);
        jTextFieldTeléfonoContacto.setEditable(true);
        jCBciudad.setEnabled(true);
    }

    
    private Empresa nuevaEmpresa() {
        Empresa e = new Empresa();
        
        e.setNombre(jTextFieldDNombres.getText());  
        e.setRuc(jTextFieldRUC.getText());
        e.setDireccion(jTextFieldDDireccion.getText());
        e.setCiudad(jCBciudad.getSelectedItem().toString());
        e.setEmail(jTextFieldDEmail.getText());
        e.setTelefono(jTextFieldDTel.getText());  
        e.setNombreContacto(jTextFieldNombreContacto.getText());
        e.setTelContacto(jTextFieldTeléfonoContacto.getText());
        e.setObservaciones(jTextFieldObservaciones.getText());
        e.setEstado("Activo");
        
        return e;
    }

    private void BotonInvisibles() {
        jButtonGuardar.setVisible(false);
        jButtonGuardarModificacion.setVisible(false);
        jButtonAtras.setVisible(false);
        jButtonModificar.setVisible(false);
        jButtonEliminar.setVisible(false);
        jButtonInsertar.setVisible(true);
        jButtonBuscar.setVisible(true);
        jButtonRealizarPago.setVisible(false);
        jButtonFacturar.setVisible(false);
        
        jLabelnomb.setVisible(false);
        jLabelruc.setVisible(false);
        jLabeltel.setVisible(false);
        jLabeldir.setVisible(false);
        jLabelemail.setVisible(false);
        jLabelncon.setVisible(false);
        jLabeltcon.setVisible(false);
        jLabelobs.setVisible(false);
        
        
    }

    private void insertarEmpresa() {
        Empresa e = nuevaEmpresa();        
        boolean v = EmpresaVista.validarEmpresa(e);
        
        if(v){            //registro validado correctamente
            int i = EmpresaControlador.insertarEmpresa(e);
            if(i>0){
                JOptionPane.showMessageDialog(null,"Se insertó correctamente", "Insertar Empresa", WIDTH );
                limpiar();
                BotonInvisibles();
            }else{
                JOptionPane.showMessageDialog(null,"No se pudo insertar", "Error", WIDTH );
            }
        }
    }

    private void escribirEmpresa(Empresa empresa) {
        if(empresa!=null){ 
            sesion.flush();
            
            jTextFieldDNombres.setText(empresa.getNombre());
            jTextFieldRUC.setText(String.valueOf(empresa.getRuc()));
            jTextFieldDTel.setText(empresa.getTelefono());
            jTextFieldDDireccion.setText(empresa.getDireccion());
            jCBciudad.setSelectedItem(empresa.getCiudad());
            jTextFieldDEmail.setText(empresa.getEmail());
            jTextFieldNombreContacto.setText(empresa.getNombreContacto());
            jTextFieldTeléfonoContacto.setText(empresa.getTelContacto());
            jTextFieldObservaciones.setText(empresa.getObservaciones());
            empresaActual = empresa;
            
            obtenerConvenios();
            obtenerEstadoCuenta();
            obtenerPendientes();
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Empresa No encontrada", "aviso", WIDTH);
            jButtonModificar.doClick();
        }   
    }

    private void actualizarEmpresa(Empresa empresa) {
        
        empresa.setNombre(jTextFieldDNombres.getText());
        empresa.setRuc(jTextFieldRUC.getText());
        empresa.setTelefono(jTextFieldDTel.getText());
        empresa.setDireccion(jTextFieldDDireccion.getText());
        empresa.setCiudad(jCBciudad.getSelectedObjects().toString());
        empresa.setEmail(jTextFieldDEmail.getText());   
        empresa.setNombreContacto(jTextFieldNombreContacto.getText());
        empresa.setTelContacto(jTextFieldTeléfonoContacto.getText());
        empresa.setObservaciones(jTextFieldObservaciones.getText());
        
    }

    private void habilitarBotones() {
        jButtonInsertar.setVisible(false);
        jButtonBuscar.setVisible(false);
        jButtonModificar.setVisible(true);
        jButtonEliminar.setVisible(true);
        jButtonAtras.setVisible(true);  
        
    }

    private void inicializarTablas() {
        tablaConvenios.addColumn("Nombre Convenio");
        tablaConvenios.addColumn("Observación");
        
        tablaPendientes.addColumn("Fecha");
        tablaPendientes.addColumn("Orden Nro");
        tablaPendientes.addColumn("Cliente");
        tablaPendientes.addColumn("Monto");
        
        tablaEstado.addColumn("Fecha");
        tablaEstado.addColumn("Descripción");
        tablaEstado.addColumn("Debe");
        tablaEstado.addColumn("Haber");    
    }

    private void obtenerConvenios() {
        listaconvenios = new ArrayList();
        listaconvenios = ConvenioControlador.BuscarConvenioEmpresa(empresaActual, sesion);
        if(listaconvenios != null){
            for(Convenio c : listaconvenios){
                Object[] f = new Object[2];
                f[0] = c.getNomConv();
                f[1] = c.getObservacion();
                
                tablaConvenios.addRow(f);
            }
        }
        
    }

    private void obtenerEstadoCuenta() {
        listaEst = new ArrayList();
        listaRec = new ArrayList();
        Object[] f = new Object[4];
        Object[] r = new Object[4];
        listaEst = EmpresaControlador.ObtenerEstadoCuenta(empresaActual, sesion);
        int saldo = 0;
        if(listaEst != null){
            for(FacturaEmpresa fe : listaEst){
                f[0] = fecha.format(fe.getFecha());
                f[1] = fe.getMovimientoEmpresa().getMovimiento();
                f[2] = formateador.format(fe.getMovimientoEmpresa().getDebe());
                f[3] = formateador.format(fe.getMovimientoEmpresa().getHaber());
                saldo = saldo + fe.getMovimientoEmpresa().getDebe() - fe.getMovimientoEmpresa().getHaber();                
                tablaEstado.addRow(f);   
                //Recupera recibos asociados a la factura crédito
                listaRec = EmpresaControlador.HistoricoRecibo(fe.getIdfacturaEmpresa(), sesion);
                if(listaRec != null){
                    for(ReciboEmpresa re : listaRec){
                        r[0] = fecha.format(re.getFecha());
                        r[1] = re.getMovimientoEmpresa().getMovimiento();
                        r[2] = formateador.format(re.getMovimientoEmpresa().getDebe());
                        r[3] = formateador.format(re.getMovimientoEmpresa().getHaber());
                        saldo = re.getMovimientoEmpresa().getDebe() - re.getMovimientoEmpresa().getHaber() + saldo;
                        tablaEstado.addRow(r);
                    }
                    r = null;
                    r =  new Object[4];
                }
                f = null;
                f = new Object[4];
            }
        }
        if(saldo > 0){
            jTextFieldSaldo.setText(formateador.format(saldo));
            jButtonRealizarPago.setVisible(true);
        }else{
            jTextFieldSaldo.setText("0");
        }
    }

    private void obtenerPendientes() {
        Object[] f = null;
        listaOrd = new ArrayList();
        listaOrd = EmpresaControlador.ordenPendiente(empresaActual, sesion);
        int total = 0;
        if(listaOrd != null){
            for(OrdenEmpresa oe : listaOrd){
                f = new Object[4];
                f[0] = fecha.format(oe.getFecha());
                f[1] = oe.getIdordenEmpresa();
                f[2] = oe.getConvPaciente().getPaciente().getNombres() + " " +  oe.getConvPaciente().getPaciente().getApellidos();
                f[3] = oe.getMonto();
                total = total + oe.getMonto();
                
                tablaPendientes.addRow(f);
                f = null;
            }
        }
        jTextFieldPendiente.setText(formateador.format(total));
        if(total > 0){
            jButtonFacturar.setVisible(true);
        }
    }

    private void deshabilitarDatos() {
        jTextFieldDNombres.setEditable(false);
        jTextFieldRUC.setEditable(false);
        jTextFieldDDireccion.setEditable(false);
        jTextFieldDEmail.setEditable(false);
        jTextFieldDTel.setEditable(false);        
        jTextFieldNombreContacto.setEditable(false);
        jTextFieldObservaciones.setEditable(false);
        jTextFieldTeléfonoContacto.setEditable(false);
        jCBciudad.setEnabled(false);
    }

    private boolean validaciones() {
        boolean v = false;
        if(jLabelnomb.isVisible() == true || jLabelruc.isVisible() == true || jLabeldir.isVisible() == true || 
                jLabelemail.isVisible() == true || jLabeltel.isVisible() == true || jLabelncon.isVisible() == true || 
                jLabeltcon.isVisible() == true || jLabelobs.isVisible() == true){
            JOptionPane.showMessageDialog(null, "Favor complete correctamente los campos");
        }else{
            v = true;
        }
        return v;
    }

    private void recuperarCiudades() {
        
        jCBciudad.removeAllItems();
        ciudades = new ArrayList<Ciudad>();
        ciudades = CiudadControlador.ListarCiudades();
        for(int i=0;i<ciudades.size();i++){
            jCBciudad.addItem(ciudades.get(i).getNombre());
        }
    }

    public void repaintForm() {
        
        if(empresaActual != null){
            Empresa e = empresaActual;
            limpiar();
            BotonInvisibles();
            
            sesion = NewHibernateUtil.getSessionFactory().openSession();
            tr = sesion.beginTransaction();
            
            empresaActual = e;
            escribirEmpresa(e);
            habilitarBotones();
            deshabilitarDatos();            
        }        
    
    }
}