/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OdontoSysPantalla;

import OdontoSysUtil.Configuraciones;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author user
 */
public class ReporteCaja extends javax.swing.JFrame {

    /**
     * Variables
     */
    Date hoy = new Date();
    SimpleDateFormat formateador = new SimpleDateFormat("yyyy/MM/dd");
    SimpleDateFormat fnormal = new SimpleDateFormat("dd/MM/yyyy");

    /**
     *
     */
    public ReporteCaja() {
        initComponents();
        
        // Setear fecha de hoy automático
        jDCF1.setDate(hoy);
        jDCF2.setDate(hoy);
        
        jLabelNot.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jDCF1 = new com.toedter.calendar.JDateChooser();
        jLabelFechaIni = new javax.swing.JLabel();
        jLabelFechaFin = new javax.swing.JLabel();
        jDCF2 = new com.toedter.calendar.JDateChooser();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelNot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/ingresar.png"))); // NOI18N
        okButton.setText("Aceptar");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 248, 110, 30));
        getRootPane().setDefaultButton(okButton);

        cancelButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/eliminar.png"))); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 248, 110, 30));

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTitulo.setText("Seleccione el rango de fechas a obtener");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 66, -1, -1));

        jDCF1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(jDCF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 107, 138, 25));

        jLabelFechaIni.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabelFechaIni.setText("Fecha Inicio");
        getContentPane().add(jLabelFechaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 107, -1, -1));

        jLabelFechaFin.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabelFechaFin.setText("Fecha Fin");
        getContentPane().add(jLabelFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 150, -1, -1));

        jDCF2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(jDCF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 145, 138, 25));

        jLabelTitulo1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabelTitulo1.setText("Reporte de Caja");
        getContentPane().add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 22, -1, -1));

        jLabelNot.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNot.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNot.setText("Seleccione dos fechas");
        getContentPane().add(jLabelNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 197, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Date f1 = jDCF1.getDate();
        Date f2 = jDCF2.getDate();
        String fechas;

        if(f1 != null && f2 != null){
            jLabelNot.setVisible(false);
            if(f1.compareTo(f2) == 0){      //Misma fecha
                fechas = "De fecha "+fnormal.format(f1);
            }else{
                fechas = "Desde "+fnormal.format(f1)+" Hasta "+fnormal.format(f2);
            }
            String ini = formateador.format(f1);
            String fin = formateador.format(f2);
            String reporte="C:\\Users\\user\\Google Drive\\UNA\\Odontosys2017\\OdontoSys\\src\\Reportes\\caja";
            Map parametros = new HashMap();
            parametros.put("fecha_ini", ini);
            parametros.put("fecha_fin", fin);
            parametros.put("fechas", fechas);
            Configuraciones.imprimirReporteHB(reporte, parametros);
        }else{
            jLabelNot.setVisible(true);
        }

    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private com.toedter.calendar.JDateChooser jDCF1;
    private com.toedter.calendar.JDateChooser jDCF2;
    private javax.swing.JLabel jLabelFechaFin;
    private javax.swing.JLabel jLabelFechaIni;
    private javax.swing.JLabel jLabelNot;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
