package OdontoSysModelo;
// Generated 08/12/2017 01:13:45 AM by Hibernate Tools 3.6.0



/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private Integer idciudad;
     private String nombre;

    public Ciudad() {
    }

    public Ciudad(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdciudad() {
        return this.idciudad;
    }
    
    public void setIdciudad(Integer idciudad) {
        this.idciudad = idciudad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


