package OdontoSysModelo;
// Generated 25/10/2017 11:24:35 AM by Hibernate Tools 3.6.0



/**
 * ConvPaciente generated by hbm2java
 */
public class ConvPaciente  implements java.io.Serializable {


     private Integer idconvPaciente;
     private Paciente paciente;
     private Convenio convenio;
     private String observacion;
     private String estado;

    public ConvPaciente() {
    }

	
    public ConvPaciente(Paciente paciente, Convenio convenio, String estado) {
        this.paciente = paciente;
        this.convenio = convenio;
        this.estado = estado;
    }
    public ConvPaciente(Paciente paciente, Convenio convenio, String observacion, String estado) {
       this.paciente = paciente;
       this.convenio = convenio;
       this.observacion = observacion;
       this.estado = estado;
    }
   
    public Integer getIdconvPaciente() {
        return this.idconvPaciente;
    }
    
    public void setIdconvPaciente(Integer idconvPaciente) {
        this.idconvPaciente = idconvPaciente;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Convenio getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(Convenio convenio) {
        this.convenio = convenio;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


