package OdontoSysModelo;
// Generated 25/10/2017 11:24:35 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Convenio generated by hbm2java
 */
public class Convenio  implements java.io.Serializable {


     private Integer idconvenio;
     private Empresa empresa;
     private String nombre;
     private String observacion;
     private String estado;
     private Set convPacientes = new HashSet(0);
     private Set detalleConvenios = new HashSet(0);

    public Convenio() {
    }

	
    public Convenio(Empresa empresa, String nombre, String estado) {
        this.empresa = empresa;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Convenio(Empresa empresa, String nombre, String observacion, String estado, Set convPacientes, Set detalleConvenios) {
       this.empresa = empresa;
       this.nombre = nombre;
       this.observacion = observacion;
       this.estado = estado;
       this.convPacientes = convPacientes;
       this.detalleConvenios = detalleConvenios;
    }
   
    public Integer getIdconvenio() {
        return this.idconvenio;
    }
    
    public void setIdconvenio(Integer idconvenio) {
        this.idconvenio = idconvenio;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getConvPacientes() {
        return this.convPacientes;
    }
    
    public void setConvPacientes(Set convPacientes) {
        this.convPacientes = convPacientes;
    }
    public Set getDetalleConvenios() {
        return this.detalleConvenios;
    }
    
    public void setDetalleConvenios(Set detalleConvenios) {
        this.detalleConvenios = detalleConvenios;
    }




}


