package OdontoSysModelo;
// Generated 01/12/2017 04:41:36 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenEmpresa generated by hbm2java
 */
public class OrdenEmpresa  implements java.io.Serializable {


     private Integer idordenEmpresa;
     private Factura factura;
     private ConvPaciente convPaciente;
     private FacturaEmpresa facturaEmpresa;
     private Date fecha;
     private String estado;
     private int monto;
     private Set detalleOrdenEmpresas = new HashSet(0);

    public OrdenEmpresa() {
    }

	
    public OrdenEmpresa(ConvPaciente convPaciente, Date fecha, String estado, int monto) {
        this.convPaciente = convPaciente;
        this.fecha = fecha;
        this.estado = estado;
        this.monto = monto;
    }
    public OrdenEmpresa(Factura factura, ConvPaciente convPaciente, FacturaEmpresa facturaEmpresa, Date fecha, String estado, int monto, Set detalleOrdenEmpresas) {
       this.factura = factura;
       this.convPaciente = convPaciente;
       this.facturaEmpresa = facturaEmpresa;
       this.fecha = fecha;
       this.estado = estado;
       this.monto = monto;
       this.detalleOrdenEmpresas = detalleOrdenEmpresas;
    }
   
    public Integer getIdordenEmpresa() {
        return this.idordenEmpresa;
    }
    
    public void setIdordenEmpresa(Integer idordenEmpresa) {
        this.idordenEmpresa = idordenEmpresa;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public ConvPaciente getConvPaciente() {
        return this.convPaciente;
    }
    
    public void setConvPaciente(ConvPaciente convPaciente) {
        this.convPaciente = convPaciente;
    }
    public FacturaEmpresa getFacturaEmpresa() {
        return this.facturaEmpresa;
    }
    
    public void setFacturaEmpresa(FacturaEmpresa facturaEmpresa) {
        this.facturaEmpresa = facturaEmpresa;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }
    public Set getDetalleOrdenEmpresas() {
        return this.detalleOrdenEmpresas;
    }
    
    public void setDetalleOrdenEmpresas(Set detalleOrdenEmpresas) {
        this.detalleOrdenEmpresas = detalleOrdenEmpresas;
    }




}


