/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OdontoSysPantallaAuxiliares;

import OdontoSysModelo.Servicio;
import OdontoSysUtil.Configuraciones;
import OdontoSysVista.ServicioVista;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tito
 */
public class BuscarServicio extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    
    public static Servicio elServicio = null;
    private DefaultTableModel tabla = new DefaultTableModel();
    

    /**
     * Creates new form BuscarServicio
     * @param parent
     * @param modal
     */
    public BuscarServicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        cargarModelo(false, "");
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(elServicio);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public Servicio getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        labelSercicio = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelDescripcion = new java.awt.Label();
        jTextFieldDescripcion = new javax.swing.JTextField();

        setTitle("Servicos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/ingresar.png"))); // NOI18N
        okButton.setText("Aceptar");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 321, -1, 30));
        getRootPane().setDefaultButton(okButton);

        cancelButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesOdontosys/DienteSanos/eliminar.png"))); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 321, -1, 30));

        labelSercicio.setAlignment(java.awt.Label.CENTER);
        labelSercicio.setBackground(new java.awt.Color(240, 240, 240));
        labelSercicio.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        labelSercicio.setText("Servicios Disponibles");
        getContentPane().add(labelSercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 452, -1));

        jTable1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTable1.setModel(tabla);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, -1, 219));

        labelDescripcion.setAlignment(java.awt.Label.RIGHT);
        labelDescripcion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        labelDescripcion.setText("Descripción");
        getContentPane().add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 105, 30));

        jTextFieldDescripcion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldDescripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                describiendokeyPress(evt);
            }
        });
        getContentPane().add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 56, 325, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        int fila = jTable1.getSelectedRow();
        if( fila > -1 ){
            elServicio = new Servicio();
            elServicio = servicios.get(fila);
            
            doClose(elServicio);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Servicio", "Buscar Servicio", WIDTH);
        }  
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(null);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(null);
    }//GEN-LAST:event_closeDialog

    private void describiendokeyPress(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_describiendokeyPress
        // TODO add your handling code here:
        String desc = jTextFieldDescripcion.getText();
        cargarModelo(rootPaneCheckingEnabled, desc);        
    }//GEN-LAST:event_describiendokeyPress

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int f = jTable1.getSelectedRow();
        String d = servicios.get(f).getDescripcion();
        jTextFieldDescripcion.setText(d);
        
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void doClose(Servicio retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BuscarServicio dialog = new BuscarServicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    //Variables
    DecimalFormat formateador = new DecimalFormat("###,###");
    ArrayList<Servicio> servicios = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDescripcion;
    private java.awt.Label labelDescripcion;
    private java.awt.Label labelSercicio;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private Servicio returnStatus = null;

    private void cargarModelo(boolean cargar, String descripcion) {
        if(cargar){          
            
            tabla = Configuraciones.limpiarModelo(tabla);
            servicios = new ArrayList();
            servicios = ServicioVista.BuscarServicio(descripcion);
            for(Servicio unServicio : servicios){
                String[] rowData = new String[3];
                rowData[0] = String.valueOf(unServicio.getIdservicio());
                rowData[1] = unServicio.getDescripcion();
                rowData[2] = String.valueOf(unServicio.getPrecio());
                
                tabla.addRow(new Object[]{rowData[0], rowData[1], formateador.format(unServicio.getPrecio())});
            }            
        }else{
            tabla.addColumn("Cod Servicio");
            tabla.addColumn("Descripcion");
            tabla.addColumn("Precio");   
            
            tabla = Configuraciones.limpiarModelo(tabla);
            servicios = new ArrayList();
            servicios = ServicioVista.BuscarServicio(descripcion);
            for(Servicio unServicio : servicios){
                String[] rowData = new String[3];
                rowData[0] = String.valueOf(unServicio.getIdservicio());
                rowData[1] = unServicio.getDescripcion();
                rowData[2] = String.valueOf(unServicio.getPrecio());
                
                tabla.addRow(new Object[]{rowData[0], rowData[1], formateador.format(unServicio.getPrecio())});
                
            } 
        }
    }
}
